catalogMode: prefer

cleanupUnusedCatalogs: true

shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar@4.0.3
  - langium@3.3.1
  - semver@6.3.1
  - valaxy-addon-waline@0.2.1
packages:
  - theme
  - demo
catalog:
  '@antfu/eslint-config': ^8.2.0
  '@iconify-json/ant-design': ^1.2.5
  '@iconify-json/simple-icons': ^1.2.79
  '@unocss/eslint-plugin': ^66.6.8
  '@vueuse/core': ^14.2.1
  bumpp: ^11.0.1
  eslint: ^10.2.1
  eslint-plugin-format: ^2.0.1
  typescript: ^6.0.3
  valaxy: ^0.28.5
  valaxy-addon-waline: ^0.2.1
  vitest: ^4.1.4
  vue-tsc: ^3.2.7
